order:
  id: O1
  status: COMPLETE

  provider:
    id: P1
    descriptor:
      name: Delhi Metro Rail Limited
      images:
        - url: https://delhimetrorail.com/logos/logo.icon

  items:
    - id: I2
      category_ids:
        - C1
        - C3
      descriptor:
        name: Metro Balance Check
        code: BALANCE_CHECK
        images:
          - url: https://delhimetrorail.com/logos/logo.ico
      price:
        currency: INR
        value: "0"
      fulfillment_ids:
        - F1

  fulfillments:
    - id: F1
      type: ONLINE
      customer:
        contact:
          email: joe.adam@abc.org
          phone: "+91-9999999999"
        person:
          name: Joe Adam
          creds:
            - id: "00129812901"
              type: CARD_IDENTIFIER
      state:
        descriptor:
          code: COMPLETED
          name: completed
      stops:
        - instructions:
            name: How to use?
            short_desc: short description about how to use?
            long_desc: Description about how to use?

  quote:
    id: Q1
    price:
      value: "0"
      currency: INR
    breakup:
      - title: CURRENT_BALANCE
        item:
          id: I2
          price:
            currency: INR
            value: "1000"

  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: BUYER_FINDER_FEES_PERCENTAGE
          value: "1"
        - descriptor:
            code: BUYER_FINDER_FEES_TYPE
          value: percent
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_BASIS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_WINDOW
          value: P30D

    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: BUYER_FINDER_FEES_PERCENTAGE
          value: "1"
        - descriptor:
            code: BUYER_FINDER_FEES_TYPE
          value: percent
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: MANDATORY_ARBITRATION
          value: "true"
        - descriptor:
            code: COURT_JURISDICTION
          value: New Delhi
        - descriptor:
            code: DELAY_INTEREST
          value: 2.5 %
        - descriptor:
            code: SETTLEMENT_AMOUNT
          value: 7 INR
        - descriptor:
            code: SETTLEMENT_TYPE
          value: upi
        - descriptor:
            code: SETTLEMENT_BANK_CODE
          value: XXXXXXXX
        - descriptor:
            code: SETTLEMENT_BANK_ACCOUNT_NUMBER
          value: xxxxxxxxxxxxxx

  billing:
    name: John Doe
    email: john.doe@example.com
    phone: "+91-9897867564"

  created_at: "2024-11-23T05:42:20.651Z"
  updated_at: "2024-11-23T05:42:20.651Z"