save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  start_location: "$.message.intent.fulfillment.stops[?(@.type=='START')].location.gps"
  intermediate_location: "$.message.intent.fulfillment.stops[?(@.type=='INTERMEDIATE_STOP')].location.gps"
  end_location: "$.message.intent.fulfillment.stops[?(@.type=='END')].location.gps"
  payment_collected_by: "$.message.intent.payment.collected_by"
  stops: "$.message.intent.fulfillment.stops[*]"
  collected_by: "$.message.intent.payment.collected_by" 
  init_provider_id: "$.message.order.provider.id"
  init_items: "$.message.order.items[*]"
  init_payments: "$.message.order.payments[*]"
  init_billing: $.message.order.billing
  init_fulfillments: "$.message.order.fulfillments[*]"
  init_tags: "$.message.order.tags"