order:
  provider:
    id: "PROVIDER_ID"
    descriptor:
      images:
        - url: "https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png"
          size_type: "sm"
      name: "ICICI Bank"
      short_desc: "ICICI Bank Ltd"
      long_desc: "ICICI Bank Ltd, India."
    tags:
      - descriptor:
          code: "CONTACT_INFO"
          name: "Contact Info"
        list:
          - descriptor:
              code: "GRO_NAME"
              name: "Gro name"
            value: "ICICI"
          - descriptor:
              code: "GRO_EMAIL"
              name: "Gro email"
            value: "lifeline@iciciprulife.com"
          - descriptor:
              code: "GRO_CONTACT_NUMBER"
              name: "Gro contact number"
            value: "1860 266 7766"
          - descriptor:
              code: "GRO_DESIGNATION"
              name: "Gro Designation"
            value: "Nodal Grievance Redressal Officer"
          - descriptor:
              code: "GRO_ADDRESS"
              name: "Gro Address"
            value: "One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013"
          - descriptor:
              code: "CUSTOMER_SUPPORT_LINK"
              name: "Customer support link"
            value: "https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1"
          - descriptor:
              code: "CUSTOMER_SUPPORT_CONTACT_NUMBER"
              name: "Customer support contact number"
            value: "1800 1080"
          - descriptor:
              code: "CUSTOMER_SUPPORT_EMAIL"
              name: "Customer support email"
            value: "customer.care@icicibank.com"
      - descriptor:
          code: "LSP_INFO"
          name: "Lsp Info"
        list:
          - descriptor:
              code: "LSP_NAME"
              name: "Lsp name"
            value: "ICICI_LSP"
          - descriptor:
              code: "LSP_EMAIL"
              name: "Lsp email"
            value: "lsp@iciciprulife.com"
          - descriptor:
              code: "LSP_CONTACT_NUMBER"
              name: "Lsp contact number"
            value: "1860 266 7766"
          - descriptor:
              code: "LSP_ADDRESS"
              name: "Lsp Address"
            value: "One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013"
    locations:
      - id: "L2"
        gps: "28.584909, 77.134029"
        descriptor:
          name: "Mumbai East"
        address: "162 Dadar, Mumbai, Maharashtra"
        area_code: "400001"

  items:
    - id: "ITEM_ID_GOLD_LOAN_2"
      descriptor:
        code: "LOAN"
        name: "Gold Loan"
      price:
        currency: "INR"
        value: "441800"
      location_ids:
        - "L2"
      tags:
        - descriptor:
            code: "LOAN_INFO"
            name: "Loan Information"
          list:
            - descriptor:
                code: "INTEREST_RATE"
                name: "Interest Rate"
                short_desc: "Loans starting from 12% (p.a)"
              value: "12%"
            - descriptor:
                code: "LTV_RATIO"
                name: "LTV Ratio"
                short_desc: "Loan to value ration (75%)"
              value: "75%"
            - descriptor:
                code: "TERM"
                name: "Loan Term"
                short_desc: "Loans Duration 5 months"
              value: "5 months"
            - descriptor:
                code: "INTEREST_RATE_TYPE"
                name: "Interest rate type"
                short_desc: "Fixed Interest type"
              value: "FIXED"
            - descriptor:
                code: "APPLICATION_FEE"
                name: "Application Fees"
                short_desc: "Application Fees"
              value: "1000 INR"
            - descriptor:
                code: "FORECLOSURE_FEE"
                name: "Foreclosure Penalty"
                short_desc: "Loan Foreclosure Penalty"
              value: "0.5%"
            - descriptor:
                code: "INTEREST_RATE_CONVERSION_CHARGE"
                name: "interest rate conversion charges"
                short_desc: "Interest rate conversion charges"
              value: "1000 INR"
            - descriptor:
                code: "DELAY_PENALTY_FEE"
                name: "Delayed payments penalty"
                short_desc: "Delayed payments penalty"
              value: "5%"
            - descriptor:
                code: "OTHER_PENALTY_FEE"
                name: "Other Penal Charges"
                short_desc: "Other Penal Charges"
              value: "1%"
            - descriptor:
                code: "ANNUAL_PERCENTAGE_RATE"
                name: "Annual Percentage Rate"
                short_desc: "Effective annualized interest rate in percentage computed on net disbursed amount using IRR approach and reducing balance method"
              value: "5%"
            - descriptor:
                code: "REPAYMENT_FREQUENCY"
                name: "Repayment Frequency"
                short_desc: "Repayment Frequency by borrower"
              value: "MONTHLY"
            - descriptor:
                code: "NUMBER_OF_INSTALLMENTS_OF_REPAYMENT"
                name: "Number of installments of repayment"
                short_desc: "Number of installments borrower has to make to payback the loan"
              value: "45"
            - descriptor:
                code: "TNC_LINK"
                name: "Terms & Conditions"
                short_desc: "Terms and Conditions"
              value: "https://icicibank.com/loan/tnc.html"
            - descriptor:
                code: "COOL_OFF_PERIOD"
                name: "cool off period"
                short_desc: "Cooling off/look-up period during which borrower shall not be charged any penalty"
              value: "PT30D"
            - descriptor:
                code: "INSTALLMENT_AMOUNT"
                name: "Installment amount"
                short_desc: "Each installment amount of repayment"
              value: "46360"
            - descriptor:
                code: "KFS_LINK"
                name: "Key Facts Statement Link"
                short_desc: "A link provided by the BPP points to a Key Fact Statement (KFS)..."
              value: "https://icicibank.com/loan/kfs-terms"
      xinput:
        form:
          id: "F03"
        form_response:
          status: "COMPLETED"
          submission_id: "F03_SUBMISSION_ID"

  quote:
    id: "LOAN_LEAD_ID_OR_SIMILAR"
    price:
      currency: "INR"
      value: "442300"
    breakup:
      - title: "PRINCIPAL"
        price:
          value: "400000"
          currency: "INR"
      - title: "INTEREST"
        price:
          value: "40000"
          currency: "INR"
      - title: "PROCESSING_FEE"
        price:
          value: "1800"
          currency: "INR"
      - title: "OTHER_UPFRONT_CHARGES"
        price:
          value: "0"
          currency: "INR"
      - title: "INSURANCE_CHARGES"
        price:
          value: "500"
          currency: "INR"
      - title: "NET_DISBURSED_AMOUNT"
        price:
          value: "397700"
          currency: "INR"
      - title: "OTHER_CHARGES"
        price:
          value: "0"
          currency: "INR"
    ttl: "PT15D"

  fulfillments:
    - type: "LOAN"
      agent:
        person:
          name: "Rajesh Sharma"
        contact:
          phone: "+91-99xx99xx99xx"
