order:
  provider:
    id: "PROVIDER_ID"

  items:
    - id: "ITEM_ID_GOLD_LOAN_2"
      descriptor:
        code: "LOAN"
        name: "Gold Loan"
      price:
        currency: "INR"
        value: "441800"
      location_ids:
        - "L2"
      xinput:
        head:
          descriptor:
            name: "JOURNEY_OFFLINE"
          index:
            min: 0
            cur: 1
            max: 1
          headings:
            - "SET_LOAN_AMOUNT"
            - "JOURNEY_OFFLINE"
        form:
          id: "FO3"
          mime_type: "application/html"
          url: "https://https://bpp.credit.becknprotocol.org/loans-details/xinput?formid=FO3"
          resubmit: false
          multiple_sumbissions: false
        required: true

  quote:
    id: "LOAN_LEAD_ID_OR_SIMILAR"
    price:
      currency: "INR"
      value: "442300"
    breakup:
      - title: "PRINCIPAL"
        price:
          value: "400000"
          currency: "INR"
      - title: "INTEREST"
        price:
          value: "40000"
          currency: "INR"
      - title: "PROCESSING_FEE"
        price:
          value: "1800"
          currency: "INR"
      - title: "OTHER_UPFRONT_CHARGES"
        price:
          value: "0"
          currency: "INR"
      - title: "INSURANCE_CHARGES"
        price:
          value: "500"
          currency: "INR"
      - title: "NET_DISBURSED_AMOUNT"
        price:
          value: "397700"
          currency: "INR"
      - title: "OTHER_CHARGES"
        price:
          value: "0"
          currency: "INR"
    ttl: "PT15D"

  fulfillments:
    - type: "LOAN"
      agent:
        person:
          name: "Rajesh Sharma"
        contact:
          phone: "+91-99xx99xx99xx"
