intent:
  category:
    descriptor:
      code: "MICRO_HOSPICASH_INSURANCE"
  provider:
    id: "P1"
    tags:
      - descriptor:
          code: "MASTER_POLICY"
        list:
          - descriptor:
              code: "POLICY_ID"
            value: "e103b4a5-10f8-42c7-b888-dbf0e2edd696"
  payment:
    collected_by: "BPP"
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: 'https://api.example-bap.com/booking/terms'
        - descriptor: 
            code: OFFLINE_CONTRACT
          value: 'true'  