save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  cancellation: "$.message.cancellation"
  order: "$.message.order"
  # start_location: "$.message.intent.fulfillment.stops[?(@.type=='START')].location.gps"
  # intermediate_location: "$.message.intent.fulfillment.stops[?(@.type=='INTERMEDIATE_STOP')].location.gps"
  # end_location: "$.message.intent.fulfillment.stops[?(@.type=='END')].location.gps"
  # payment_collected_by: "$.message.intent.payment.collected_by"
  # stops: "$.message.intent.fulfillment.stops[*]"
  # collected_by: "$.message.intent.payment.collected_by" 